### ISSUE TITLE
画像をカルーセルとかにしていい感じにする

### ISSUE THREAD

**Issue by euxn23** [euxn23/sana_natori_dev#3]

**Comment by naporin0624** [comment]
やります〜これ今日の夜くらいに

**Comment by euxn23** [comment]
- カルーセルだけどアイテムの移動はつねに動いてる感じ(シュッ……シュッ……ではなくツーーーーーーという感じ)
- ページロード時にカルーセルのアイテムたちが高速で流れ、シューーーーンと通常速度に落ち着く

**Comment by euxn23** [comment]
カルーセル実装をするにあたっては上記のアニメーションを満たせる実装で着手しないとダメそう。
以下のライブラリは試したけどだめ
- react-slick: flex 非対応
- nuka-carousel: アイテムの移動アニメーションがカクカク、最速値が遅い

**Comment by euxn23** [comment]
実装しました
細かい調整は #9 #10 で 🙏
